// <auto-generated />
namespace WebBookStore.Migrations.Store
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialStore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialStore));
        
        string IMigrationMetadata.Id
        {
            get { return "202510111243235_InitialStore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
